apiVersion: v1
kind: Service
metadata:
  name: {{ include "recipes.backend.serviceName" . }}
  labels:
    {{- include "recipes.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: http
      name: http
  selector:
    {{- include "recipes.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
