#!/usr/bin/env bash
# Re-tag the locally-built recipes images for ttl.sh, push them, and emit a
# values override file you can pass to `helm upgrade -f`.
#
# ttl.sh is an anonymous, ephemeral OCI registry: images are deleted after the
# TTL embedded in the tag (max 24h). See https://ttl.sh.
#
# Secrets are sourced from backend/.env and agent/.env (agent overrides
# backend) and baked into the generated values file. The output lives under
# temp/ and is gitignored — do not check it in.
#
# Env vars:
#   TTL            ttl.sh expiry tag — e.g. 30m, 1h, 4h, 24h (default 4h)
#   TAG            source image tag to publish (default latest)
#   DOCKER_USER    owner segment of the local images (default juancavallotti)
#   TTLSH_PREFIX   path prefix under ttl.sh/ (default: $DOCKER_USER)
#   TTLSH_REGISTRY override the registry hostname (default ttl.sh)
#   OUT_FILE       where to write the generated values file
#                  (default temp/values.ttlsh.yaml)
#   INGRESS_ENABLED  enable the ingress in generated values (default false)
#   INGRESS_HOST     ingress host when enabled (default recipes.local)
set -euo pipefail

TTL="${TTL:-4h}"
SOURCE_TAG="${TAG:-latest}"
DOCKER_USER="${DOCKER_USER:-juancavallotti}"
REGISTRY="${TTLSH_REGISTRY:-ttl.sh}"
PREFIX="${TTLSH_PREFIX:-${DOCKER_USER}}"
OUT_FILE="${OUT_FILE:-temp/values.ttlsh.yaml}"
INGRESS_ENABLED="${INGRESS_ENABLED:-false}"
INGRESS_HOST="${INGRESS_HOST:-recipes.local}"

case "$INGRESS_ENABLED" in
  true|false) ;;
  *)
    echo "INGRESS_ENABLED must be 'true' or 'false' (got '$INGRESS_ENABLED')" >&2
    exit 1
    ;;
esac

case "$TTL" in
  *m|*h) ;;
  *)
    echo "TTL must end in 'm' or 'h' (got '$TTL'); e.g. 30m, 1h, 4h, 24h" >&2
    exit 1
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

load_env_file() {
  local f="$1"
  if [ -f "$f" ]; then
    echo "==> Loading env from ${f#${REPO_ROOT}/}"
    set -a
    # shellcheck disable=SC1090
    . "$f"
    set +a
  fi
}
load_env_file "$REPO_ROOT/backend/.env"
load_env_file "$REPO_ROOT/agent/.env"

DB_USER="${DB_USER:-postgres}"
DB_PASSWORD="${DB_PASSWORD:-postgres}"
DB_NAME="${DB_NAME:-recipes}"
GEMINI_API_KEY="${GEMINI_API_KEY:-}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"

if [ -z "$GEMINI_API_KEY" ]; then
  echo "warning: GEMINI_API_KEY not set in agent/.env — agent will fail to start in-cluster." >&2
fi
[ -n "$OPENAI_API_KEY" ]    && echo "==> Including OPENAI_API_KEY in generated secret"
[ -n "$ANTHROPIC_API_KEY" ] && echo "==> Including ANTHROPIC_API_KEY in generated secret"

# Pairs of local image name + helm values key. Kept as parallel scalars so the
# script runs on bash 3.2 (macOS default) without needing associative arrays.
IMAGES="recipes-db:postgres recipes-api:backend recipes-agent:agent recipes-web:web"

mkdir -p "$(dirname "$OUT_FILE")"

POSTGRES_REPO=""
BACKEND_REPO=""
AGENT_REPO=""
WEB_REPO=""

for entry in $IMAGES; do
  name="${entry%%:*}"
  helm_key="${entry##*:}"
  src="${DOCKER_USER}/${name}:${SOURCE_TAG}"
  dest_repo="${REGISTRY}/${PREFIX}/${name}"
  dest_ref="${dest_repo}:${TTL}"

  if ! docker image inspect "$src" >/dev/null 2>&1; then
    echo "Local image $src not found — run 'task build:images' first." >&2
    exit 1
  fi

  echo "==> Tagging  $src -> $dest_ref"
  docker tag "$src" "$dest_ref"
  echo "==> Pushing  $dest_ref"
  docker push "$dest_ref"

  case "$helm_key" in
    postgres) POSTGRES_REPO="$dest_repo" ;;
    backend)  BACKEND_REPO="$dest_repo" ;;
    agent)    AGENT_REPO="$dest_repo" ;;
    web)      WEB_REPO="$dest_repo" ;;
  esac
done

# Escape a string for safe inclusion inside a double-quoted YAML scalar.
yaml_escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

cat > "$OUT_FILE" <<EOF
# Generated by scripts/ttlsh-publish.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Images live on ${REGISTRY} and expire ${TTL} after push time.
# Re-run \`task publish:ttlsh\` to refresh them before they expire.
# Secrets sourced from backend/.env then agent/.env (agent wins on conflicts).
# Gitignored — do not commit.
postgres:
  image:
    repository: ${POSTGRES_REPO}
    tag: "${TTL}"
    pullPolicy: Always
  auth:
    username: "$(yaml_escape "$DB_USER")"
    password: "$(yaml_escape "$DB_PASSWORD")"
    database: "$(yaml_escape "$DB_NAME")"
backend:
  image:
    repository: ${BACKEND_REPO}
    tag: "${TTL}"
    pullPolicy: Always
agent:
  image:
    repository: ${AGENT_REPO}
    tag: "${TTL}"
    pullPolicy: Always
  geminiApiKeySecret:
    create: true
    value: "$(yaml_escape "$GEMINI_API_KEY")"
  openaiApiKeySecret:
    value: "$(yaml_escape "$OPENAI_API_KEY")"
  anthropicApiKeySecret:
    value: "$(yaml_escape "$ANTHROPIC_API_KEY")"
web:
  image:
    repository: ${WEB_REPO}
    tag: "${TTL}"
    pullPolicy: Always
ingress:
  enabled: ${INGRESS_ENABLED}
  host: "$(yaml_escape "$INGRESS_HOST")"
EOF

echo
echo "Wrote $OUT_FILE"
echo
echo "Deploy with:"
echo "  helm upgrade --install recipes helm -f $OUT_FILE"
